### ISSUE TITLE
eslint-disable for Config.d.ts

### ISSUE THREAD

**Issue by iwata** [tusharmath/node-config-ts#24]
I'm using ESLint with TypeScript and recently the roadmap of TypeScript announce that the team will be focusing on ESLint.
[The future of TypeScript on ESLint \- ESLint \- Pluggable JavaScript linter](https://eslint.org/blog/2019/01/future-typescript-eslint)
So, I wanna add a comment to disable ESLint, too.

**Comment by tusharmath** [comment]
Are you saying you want to disable eslint on the generated `Config.d.ts` file?

**Comment by iwata** [comment]
Yes.

**Comment by tusharmath** [comment]
Added the eslint disable comment. Hope it helps.

**Comment by iwata** [comment]
Yes, please add `eslint-disable` comment looks like `tslint:disable`.

**Comment by tusharmath** [comment]
Feature deployed here — https://github.com/tusharmath/node-config-ts/releases/tag/v2.2.0

**Comment by iwata** [comment]
Thanks!
