### ISSUE TITLE
TS config declaration

### ISSUE THREAD

**Issue by kusyka911** [tusharmath/node-config-ts#40]
Can you add analyze of all config files and add optional type like this:
```
interface Config {
  serverUrl: string;
  cdnUrl?: string | string[];
}
```

**Comment by tusharmath** [comment]
Can you elaborate a bit more on the use case?

**Comment by kusyka911** [comment]
> Can you elaborate a bit more on the use case?
![image](https://user-images.githubusercontent.com/24293461/63268575-26e97980-c29d-11e9-8bd5-925d7213f857.png)

"storageProfile" must be optional, I don't want to use it in the default config file, but for correct confg.d.ts generation. I need to set it as an empty string, and only to empty string, null or undefined will throw new errors in my code.
So parsing of all project configs would be a nice solution to generate correct optional types and something like (string | string[]) in config.d.ts file.
![image](https://user-images.githubusercontent.com/24293461/63267711-55feeb80-c29b-11e9-89c0-a814e2eb66b7.png)
```
  "environment": "@@NODE_ENV",
```
p.s. undefined type for environment variables (must be a "string | undefined")

**Comment by tusharmath** [comment]
Got it @Neko911 thanks for the detailed explanation :)

One of the recommended ways to solve your problem is to have a boolean setting — 

```json
"storageProfile": {
  "enabled": false,
  "value": "__DEFAULT_STORAGE_PROFILE__"
}
```

There is no practical way of otherwise figuring out if the key is optional.

**Comment by kusyka911** [comment]
I was also thinking about something like this, but more detailed type declaration generation is necessary. There is not only optional parameters problem, as I wrote.
