### ISSUE TITLE
Use environment variable USERNAME instead of USER on Windows OS

### ISSUE THREAD

**Issue by ivosh** [tusharmath/node-config-ts#42]
Windows OS uses `USERNAME` environment variable to convey the same meaning as `USER` on UNIXes.

However `node-config-ts` currently tries to locate user-specific config only based on `USER`.
This suits Linux, *BSD and Solaris users, but not Windows ones.

I'd like propose to check also USERNAME environment variable if USER is not set.

**Comment by ivosh** [comment]
Will prepare a PR shortly.

**Comment by ivosh** [comment]
Thank you for merging PR #43.
Could we expect a release any soon?

**Comment by tusharmath** [comment]
Weird it’s supposed to be auto published. I’ll check

Tushar Mathur
tusharmath.com ( https://tusharmath.com )
