### ISSUE TITLE
Support of hjson or json5

### ISSUE THREAD

**Issue by na-ji** [tusharmath/node-config-ts#69]
Hello,

This is a feature request: the support of [hjson](https://hjson.github.io/) or [json5](https://json5.org/) for the config files. Those two formats have useful features, but the most interesting one is the ability to write comments, which is more user-friendly. 

Thanks.

**Comment by quintenbox** [comment]
Good suggestion @na-ji, I would love to have the ability to use json5 as well!

**Comment by tusharmath** [comment]
Resolved in #73
